### ISSUE TITLE
pq 训练过程中出现core 文件，有截图看堆栈信息

### ISSUE THREAD

**Issue by zhangwei-okok** [orcadt/ivf-hnsw#24]
![image](https://user-images.githubusercontent.com/68059845/92209284-5296cc00-eebf-11ea-9752-673998dd2f1d.png)

**Comment by flydt** [comment]
faiss 编译选项的问题，这个版本的 faiss 不支持 -O3 优化，用 -O2 即可修复，已经修改 CMakeList.txt 文件解决
