### ISSUE TITLE
build index 里面出现core 文件，见截图

### ISSUE THREAD

**Issue by zhangwei-okok** [orcadt/ivf-hnsw#25]
![image](https://user-images.githubusercontent.com/68059845/92367621-3bf3ad80-f129-11ea-8050-93158f3aafd5.png)

**Comment by flydt** [comment]
ivf-hnsw 绑定的 faiss 版本有 BUG，不能以 -ofast 级别正确编译，会 core 掉，修改为 -o2 解决问题
