### ISSUE TITLE
build_batchs_to_index() 中重复判断没有创建预索引的情况

### ISSUE THREAD

**Issue by hzzoky** [orcadt/ivf-hnsw#26]
![image](https://user-images.githubusercontent.com/68095938/92377465-c55dac80-f136-11ea-88d9-a1c405aaf937.png)
![image](https://user-images.githubusercontent.com/68095938/92377551-e4f4d500-f136-11ea-8d97-eb0fa0d2cfa4.png)

**Comment by flydt** [comment]
bug 已修复
